# Generated by Django 3.1.2 on 2020-11-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('cover_img_url', models.TextField()),
                ('url', models.TextField()),
                ('start_date', models.DateField(auto_now=True)),
                ('viewd_times', models.IntegerField(default=0)),
                ('favorite', models.IntegerField(default=0)),
            ],
        ),
    ]
