# Generated by Django 3.1.2 on 2020-11-02 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebSites',
            new_name='WebSite',
        ),
    ]
