# Generated by Django 3.1.2 on 2020-11-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20201102_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
