# Generated by Django 3.1.2 on 2020-11-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20201103_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='cover_img',
            field=models.ImageField(blank=True, default=None, upload_to='images/sites/'),
        ),
        migrations.AlterField(
            model_name='website',
            name='cover_img_url',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
    ]
