# Generated by Django 3.1.2 on 2020-11-03 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20201103_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='cover_img',
        ),
    ]
