# Generated by Django 3.1.2 on 2020-11-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_website_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='cover_img',
            field=models.ImageField(blank=True, default=None, upload_to='images/sites/'),
            preserve_default=False,
        ),
    ]
