# Generated by Django 3.1.2 on 2020-11-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_website_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='cover_img',
            field=models.ImageField(default=None, null=True, upload_to='images/sites/'),
        ),
    ]
