# Generated by Django 3.1.2 on 2020-11-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_remove_website_cover_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='website',
            name='cover_img_url',
        ),
        migrations.AddField(
            model_name='website',
            name='cover_img',
            field=models.ImageField(default='', upload_to='images/sites/'),
        ),
    ]
