# Generated by Django 3.1.2 on 2020-11-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_auto_20201103_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='avatar',
            field=models.ImageField(default='', upload_to='images/users/'),
        ),
    ]
