# Generated by Django 3.1.2 on 2020-11-03 08:50

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_staff_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='avatar',
            field=models.ImageField(default='images/logo.png', upload_to=index.models.user_avatar_path),
        ),
        migrations.AlterField(
            model_name='website',
            name='cover_img',
            field=models.ImageField(default='images/logo.png', upload_to=index.models.sites_cover_path),
        ),
    ]
