# Generated by Django 3.1.3 on 2021-01-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_auto_20201103_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='ip_addr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
