# Generated by Django 3.1.3 on 2021-01-09 12:29

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_auto_20210109_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('abstract', models.TextField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('viewed_times', models.IntegerField(default=0)),
                ('favorite', models.IntegerField(default=0)),
                ('cover_img', models.ImageField(default='images/logo.png', upload_to=index.models.sites_cover_path)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('modified_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='website',
            old_name='viewd_times',
            new_name='viewed_times',
        ),
        migrations.AlterField(
            model_name='staff',
            name='profile',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='website',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='website',
            name='ip_addr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
